services:
  app:
    build: .
    restart: unless-stopped
    ports:
      - "8080:8080"
    # environment:
    #   - DB_HOST=db
    #   - DB_PORT=5432
    #   - DB_USER=postgres
    #   - DB_PASSWORD=postgres
    #   - DB_NAME=appdb
    depends_on:
      - db
    networks:
      - app-network
    env_file: ".env"

  db:
    image: postgres:latest
    restart: unless-stopped
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=appdb
    # volumes:
    #   - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge

